package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/app") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private ZipresultsRepository ZipresultsRepository;

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Zipresults> getAllZipresults() {
    // This returns a JSON or XML with the users
    return ZipresultsRepository.findAll();
  }
  
  @GetMapping(path="/zip/{zip}")
  public @ResponseBody Iterable<Zipresults> getZipresults(@PathVariable(name="zip") String zip) {
	  if (zip == null) {
          return null;// throws JsonMappingException, JsonProcessingException
      } else {
    	  return ZipresultsRepository.getZipresults(zip);
      }
  }
}